name: softleticspro_ims_flutter
description: "Internal team management system for softleticsPro Solutions"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.48
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  